framework: jasmine
launch_in_dev:
  - PhantomJS
  - Node
launchers:
  Node:
    command: npm run test-server
src_files:
  - tram-one.js
  - tests/specs/*.js
test_page: tests/testem.html
before_tests: npm run test-build
parallel: 10
