framework: jasmine
host: 127.0.0.1
launch_in_dev:
  - Chrome
  - Firefox
  - Node
browser_args:
  Chrome:
    mode: dev
    args:
      - --headless
      - --disable-gpu
      - --remote-debugging-port=9222
      - --no-sandbox
  Firefox:
    mode: dev
    args:
      - --headless
launchers:
  Node:
    command: npm run test-server
src_files:
  - tram-one.js
  - tests/specs/*.js
test_page: tests/testem.html
before_tests: npm run test-build
parallel: 10
